language: node_js
node_js:
  - 12
before_install:
    - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
cache:
  directories:
    - ~/.npm
jobs:
  include:
    - stage: test
      script:
        - npm run test:coverage
    - stage: publish
      if: branch = master
      script:
        - npm config set access public
        - npm run release
