language: node_js
node_js:
  - 10
cache:
  directories:
    - ~/.npm
jobs:
  include:
    - stage: test
      script:
        - npm run test:coverage
    - stage: publish
      if: branch = master
      script:
        - npm config set access public
        - npm run release
