version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    container_name: localstack
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - SERVICES=dynamodb
    volumes:
      - './.aws-local:/docker-entrypoint-initaws.d'
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
