version: 2.1

orbs:
    node: circleci/node@3.0.0

jobs:
    build:
        working_directory: ~/app
        docker:
            -   image: gplane/pnpm:6.32-node16-alpine
        steps:
            - checkout
            -   restore_cache:
                    key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
            -   run:
                    name: Install
                    command: pnpm install --frozen-lockfile
            -   save_cache:
                    key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
                    paths:
                        - node_modules
                            - .
            -   persist_to_workspace:
                    root: .
                    paths:
                        - .

    test:
        docker:
            -   image: gplane/pnpm:6.32-node16-alpine
        steps:
            -   attach_workspace:
                    at: .
            -   run:
                    name: Lint
                    command: npm run lint
            -   run:
                    name: Test
                    command: npm run test
    release:
        docker:
            -   image: gplane/pnpm:6.32-node16-alpine
        steps:
            -   attach_workspace:
                    at: .
            -   run:
                    name: Release
                    command: |
                        printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
                        npm config set access public
                        npm run release
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            -   test:
                    requires:
                        - build
            -   release:
                    requires:
                        - build
                        - test
                    filters:
                        branches:
                            only:
                                - master
