version: 2.1

orbs:
    node: circleci/node@3.0.0

jobs:
    build:
        working_directory: ~/app
        executor:
            name: node/default
            tag: '16.13'
        steps:
            - checkout
            -   run:
                    name: install-npm
                    command: npm install -g pnpm@6.30.1
            -   restore_cache:
                    key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
            -   run:
                    name: Install
                    command: pnpm install --frozen-lockfile
            -   save_cache:
                    key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
                    paths:
                        - node_modules
                            - .

    test:
        docker:
            -   image: cimg/node:16.13
        steps:
            -   attach_workspace:
                    at: .
            -   run:
                    name: Lint
                    command: npm run lint
            -   run:
                    name: Test
                    command: npm run test
    release:
        docker:
            -   image: cimg/node:16.13
        steps:
            -   attach_workspace:
                    at: .
            -   run:
                    name: Release
                    command: |
                        printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
                        npm config set access public
                        mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
                        npm run release
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            -   test:
                    requires:
                        - build
            -   release:
                    requires:
                        - build
                        - test
                    filters:
                        branches:
                            only:
                                - master
