version: 2.1

orbs:
    node: circleci/node@3.0.0

jobs:
    build:
        working_directory: ~/app
        executor:
            name: node/default
            tag: '16.13'
        steps:
            - checkout
            -   node/install-npm:
                    version: '8.5'
            -   node/install-packages:
                    app-dir: ~/app
                    cache-path: node_modules
            -   persist_to_workspace:
                    root: .
                    paths:
                        - .

    test:
        docker:
            -   image: cimg/node:12.16
        steps:
            -   attach_workspace:
                    at: .
            -   run:
                    name: Lint
                    command: npm run lint
            -   run:
                    name: Test
                    command: npm run test:coverage
            -   store_artifacts:
                    path: coverage
                    destination: coverage
    release:
        docker:
            -   image: cimg/node:12.16
        steps:
            -   attach_workspace:
                    at: .
            -   run:
                    name: Release
                    command: |
                        printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
                        npm config set access public
                        mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
                        npm run release
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            -   test:
                    requires:
                        - build
            -   release:
                    requires:
                        - build
                        - test
                    filters:
                        branches:
                            only:
                                - master
