version: 2.1

orbs:
    node: circleci/node@3.0.0

jobs:
    build:
        working_directory: ~/app
        docker:
            -   image: gplane/pnpm:6.32-node16-alpine
        steps:
            - checkout
            -   restore_cache:
                    key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
            -   run:
                    name: Install
                    command: pnpm install --frozen-lockfile
            -   save_cache:
                    key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
                    paths:
                        - node_modules
                            - .
            -   persist_to_workspace:
                    root: .
                    paths:
                        - .

    test:
        docker:
            -   image: gplane/pnpm:6.32-node16-alpine
        steps:
            -   attach_workspace:
                    at: .
            -   run:
                    name: Lint
                    command: npm run lint
            -   run:
                    name: Test
                    command: npm run test
    release:
        docker:
            -   image: gplane/pnpm:6.32-node16-bullseye
        steps:
            -   add_ssh_keys:
                    fingerprints:
                        - "5e:92:8a:61:f2:e8:b9:28:81:05:7c:7c:ee:27:13:93"
            -   attach_workspace:
                    at: .
            -   run:
                    name: Release
                    command: |
                        printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
                        npm config set access public
                        git config --global user.email vdtn359@gmail.com
                        git config --global user.name "Tuan Nguyen"
                        mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
                        npm run release
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            -   test:
                    requires:
                        - build
            -   release:
                    requires:
                        - build
                        - test
                    filters:
                        branches:
                            only:
                                - master
