version: '3.3'
services:
    db:
        platform: linux/amd64
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'test'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '13306:3306'
        expose:
            - '13306'
        volumes:
            - my-db:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/my.cnf
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
    localstack:
        image: localstack/localstack
        network_mode: bridge
        ports:
            - "127.0.0.1:4510-4559:4510-4559"  # external service port range
            - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
        environment:
            - DEBUG=1
            - DATA_DIR=${DATA_DIR-}
            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
            - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
            - LOCALSTACK_SERVICES=s3,sns,sqs,kinesis
            - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
            - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - ./docker/localstack/init:/docker-entrypoint-initaws.d
volumes:
    my-db:
