export enum GenericErrorCodes {
	// general codes
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	INVALID_VALUE = 'INVALID_VALUE',
	INVALID_EMAIL = 'INVALID_EMAIL',
	INVALID_BOOLEAN = 'INVALID_BOOLEAN',
	INVALID_LENGTH = 'INVALID_LENGTH',
	INVALID_NUMBER = 'INVALID_NUMBER',
	INVALID_PASSWORD = 'INVALID_PASSWORD',
	INVALID_PHONE = 'INVALID_PHONE',
	INVALID_URL = 'INVALID_URL',
	INVALID_IBAN = 'INVALID_IBAN',
	INVALID_BIC = 'INVALID_BIC',
	INVALID_DATE = 'INVALID_DATE',
	INVALID_POSTAL_CODE = 'INVALID_POSTAL_CODE',
	VALUE_TOO_SMALL = 'VALUE_TOO_SMALL',
	VALUE_TOO_BIG = 'VALUE_TOO_BIG',
	VALUE_REQUIRED = 'VALUE_REQUIRED',
}
